-- TripPilot Supabase schema for passenger and trip storage
-- Authentication remains local/mock for now; this migration only covers trip/passenger data.

create extension if not exists pgcrypto;

create table if not exists public.passengers (
  id bigint generated by default as identity primary key,
  passenger_code text not null unique,
  user_id text not null,
  name text not null,
  age integer,
  gender text,
  phone text,
  email text,
  passport text,
  government_id text,
  emergency_contact text,
  frequent_flyer_number text,
  travel_preferences text,
  mode text not null default 'demo' check (mode in ('demo', 'real')),
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id text not null,
  passenger_id bigint references public.passengers(id) on delete cascade,
  pnr text,
  flight_number text,
  airline text,
  aircraft_type text,
  source_airport text,
  destination_airport text,
  departure_terminal text,
  arrival_terminal text,
  departure_gate text,
  arrival_gate text,
  departure_time text,
  arrival_time text,
  duration text,
  layover_details text,
  stops integer default 0,
  fare numeric(12,2) default 0,
  seat text,
  cabin_class text,
  meal text,
  baggage_allowance text,
  refund_policy text,
  cancellation_policy text,
  flight_status text,
  booking_website text,
  source text default 'manual' check (source in ('manual', 'imported')),
  mode text not null default 'demo' check (mode in ('demo', 'real')),
  created_at timestamptz not null default now()
);

create index if not exists passengers_user_mode_idx on public.passengers(user_id, mode);
create index if not exists trips_user_mode_idx on public.trips(user_id, mode);
create index if not exists trips_passenger_idx on public.trips(passenger_id);
